### ISSUE TITLE
Create the list of topics

### ISSUE THREAD

**Issue by SayaniG371** [SayaniG371/PyMaster#1]
Make a list of all the basic but important topics for learning python in a .md file
For example, variables, conditions, loops, etc in python

**Comment by RushiVachhani** [comment]
I would like to take it up, if you don't mind.

**Comment by SayaniG371** [comment]
Ok sure go ahead!

**Comment by RushiVachhani** [comment]
what the file name should be ?

**Comment by RushiVachhani** [comment]
opened a pull request check it out.
